sudo: required
dist: bionic
language: c
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - autoconf
      - automake
      - make
      - xutils-dev
      - libpango1.0-dev
      - libcairo2-dev
      - libstartup-notification0-dev
      - libxcb-ewmh-dev
      - libxcb-icccm4-dev
      - libxcb-util0-dev
      - libxcb-xinerama0-dev
      - libxcb-xkb-dev
      - libxcb-randr0-dev
      - libxcb1-dev
      - libxkbcommon-x11-dev
      - libxkbcommon-dev
      - texinfo

before_install:
  - sudo add-apt-repository -y 'deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse'
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y --force-yes flex/trusty-backports libfl-dev/trusty-backports
  - git clone --recursive https://github.com/Airblader/xcb-util-xrm.git
  - cd xcb-util-xrm
  - ./autogen.sh --prefix=/usr
  - make
  - sudo make install
  - cd -
  - git clone https://github.com/libcheck/check/ -b 0.11.0
  - cd check
  - autoreconf -i
  - TEX="false" ./configure --prefix=/usr/
  - make
  - sudo make install
  - cd -
  - git clone --recursive https://github.com/davatorium/rofi
  - cd rofi
  - git checkout 1.5.4
  - autoreconf -i
  - ./configure
  - make
  - sudo make install
  - cd -

script:
  - autoreconf -i
  - ./configure
  - make
